title: Di Pan's Homepage
page-top-title: Di Pan
top-section-bg-text: New-Generation Electronic Information Technology 
home-subtitle: Di Pan&ensp;|&ensp;狄攀
copyright-text: '&copy; Sen Li 2024-2025. All Rights Reserved.'
